; game.inc - ゲーム
;


; フレーム
;
    defc    GAME_FRAME_INTERVAL                         =   5

; 道
;
    defc    GAME_ROAD_SIZE                              =   25
    defc    GAME_ROAD_START_X                           =   16
    defc    GAME_ROAD_START_Y                           =   11
    defc    GAME_ROAD_STRAIGHT_Y                        =   GAME_ROAD_START_Y + 8
    defc    GAME_ROAD_LIMIT_LEFT                        =   0
    defc    GAME_ROAD_LIMIT_RIGHT                       =   32
    defc    GAME_ROAD_SAFETY_LEFT                       =   2
    defc    GAME_ROAD_SAFETY_RIGHT                      =   5

; ペンペン
;
    defc    GAME_PENPEN_START_X                         =   19
    defc    GAME_PENPEN_Y                               =   11
    defc    GAME_PENPEN_LIMIT_LEFT                      =   1
    defc    GAME_PENPEN_LIMIT_RIGHT                     =   38
    defc    GAME_PENPEN_TILESET                         =   9
    defc    GAME_PENPEN_TILESET_SIZE                    =   9
    defc    GAME_PENPEN_TILESET_SIZE_X                  =   3
    defc    GAME_PENPEN_TILESET_SIZE_Y                  =   3
    defc    GAME_PENPEN_ANIMATION_SIZE                  =   2


; 関数の宣言
;


; 変数の宣言
;

